name: WindowsCI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=appJava/libs/DS-Desktop-Notify.jar -DgroupId=ds.descktop -DartifactId=DS-Desktop-Notify -Dversion=v0.91 -Dpackaging=jar -DgeneratePom=true
          mvn -B package --file appJava/pom.xml
      - name: Build Windows App
        run: |
          jpackage \
            --name CreadorCraftLan \
            --app-version 1.0 \
            --input appJava/target/ \
            --main-jar CreadorCraftLan-1.0.0-beta.jar \
            --main-class org.CreadoresProgram.CreadorCraftLan.MainActivity \
            --icon appJava/src/main/resources/iclauncher.ico \
            --type exe \
            --file-associations resourcesWindows/opencreadorcraftlan.assoc \
            --dest appJava/target/image \
            --verbose
      - name: UploadArtifact
        uses: actions/upload-artifact@v4
        with:
          name: CreadorCraftLan-Linux
          path: appJava/target/image/*
